INSERT INTO "TODO_T" (ID, NAME, STATUS) VALUES (NEXTVAL('TODO_S'), 'Grocery shopping', 'ACTIVE');
INSERT INTO "TODO_T" (ID, NAME, STATUS) VALUES (NEXTVAL('TODO_S'), 'Drop son to the school', 'COMPLETED');
INSERT INTO "TODO_T" (ID, NAME, STATUS) VALUES (NEXTVAL('TODO_S'), 'Pick up son from the school', 'ACTIVE');
COMMIT;