INSERT INTO "TODO_T" (ID, NAME, STATUS) VALUES (NEXTVAL('TODO_S'), 'TEST Grocery shopping', 'ACTIVE');
INSERT INTO "TODO_T" (ID, NAME, STATUS) VALUES (NEXTVAL('TODO_S'), 'TEST Drop son to the school', 'COMPLETED');
INSERT INTO "TODO_T" (ID, NAME, STATUS) VALUES (NEXTVAL('TODO_S'), 'TEST Pick up son from the school', 'ACTIVE');
COMMIT;